### ISSUE TITLE
Bug in package

### ISSUE THREAD

**Issue by MansMeg** [thozh912/Lab6#1]
Hi!

Im having problems with testing your package (test 2-6 fails)? And I can't read your vignette using vignette('lab_report_knapsack') after I have installed your package with:
```
devtools::install_github("thozh912/Lab6", build_vignettes = TRUE)
```

**Comment by thozh912** [comment]
Hi,

Yes, it appears something is wrong. How fix following?

The functions work as they should when we test them in console, but they
return a different, smaller result when run in test_that().
we managed to fix two regarding value returned by setting tolerance=1 in
expect_equal(), but we cant seem to fix the other two regarding  which
elements returned.
I commented the unfixable tests.

The Vignette wasn't updated in inst file. Now it is but build_vignettes()
gives error when trying to call

brute_force_knapsack(knapsack_matr[1:9,], W = 2000)

note that it seems to think knapsack_matr has length 0, while it is a 9 x 2
matrix.

Quitting from lines 68-74 (lab_report_knapsack.rmd) Error: processing
vignette 'lab_report_knapsack.rmd' failed with diagnostics:
dims [product 18] do not match the length of object [0]

**Comment by MansMeg** [comment]
Hi!
Both those problems are problems due to your own code so it is hard to debug them without sitting down with your code. I saw that there is different functions use to generate different knapsack datasets. Maybe this is a problem?

Regarding the test suite I do not understand what you mean by test ing the console. Do you run the whole test_Lab6.R and it works?

/Måns

**Comment by thozh912** [comment]
Hi,

We fixed the Vignette problem. Somehow it was comment error. is # not
enough for comment?
Rregards the test suite its a more general problem. What I meant earlier is
we run the functions in console in order to test output.
Well, it turns out even when you set.seed(), runif() generates different
output depending on whether you are running windows or mac
(or maybe different versions of R).

anyhow I will let the mac user (who is reading this mail chain) do the test
suite.

Regards

A&T

**Comment by MansMeg** [comment]
Great, so everything should work now?

It should be platform independent the random seeds, but it can be so that different version has different standard rngs, but that seems strange. I cant find anything on this behaviour you mentioned.

**Comment by thozh912** [comment]
Yes,every thing seems to work, though build Vignette takes 2 min.

We have a question regarding Lab7 train with method = "lm". We have not
been able to run it. How fix this? We get

> lmfit <- train(crim ~. ,+                data = training,+                method ="lm",+                na.action = na.omit+               #trControl = ctrl+                #preProc = c("center","scale"),+                )Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared
 Min.   : NA   Min.   : NA
 1st Qu.: NA   1st Qu.: NA
 Median : NA   Median : NA
 Mean   :NaN   Mean   :NaN
 3rd Qu.: NA   3rd Qu.: NA
 Max.   : NA   Max.   : NA
 NA's   :1     NA's   :1    Error in train.default(x, y, weights = w,
...) : StoppingIn addition: There were 26 warnings (use warnings() to
see them)


same call with method = "leapForward"  works though.
T&A

**Comment by MansMeg** [comment]
Hi!

I do not know why that happend with "lm" (have not tried this myself) so it
is hard to help you over e-mail. I can't find any bug reported in the caret
package issue list at github som my first guess is that there is something
wrong with your code.

Ive now corrected your lab/package and it looks really nice. Good work guys!

**Comment by MansMeg** [comment]
So you can close this issue now if you want to... =)

**Comment by thozh912** [comment]
closing
